const {
  VITE_SERVICE_ID: SERVICE_ID,
  VITE_TEMPLATE_ID: TEMPLATE_ID,
  VITE_PUBLIC_KEY: PUBLIC_KEY,
  VITE_USER_ID: USER_ID,
} = import.meta.env;

export { SERVICE_ID, TEMPLATE_ID, PUBLIC_KEY, USER_ID };
