import { TechnologiesData } from '@/models';

export const technologies: TechnologiesData = {
  android: { name: 'android', url: 'https://www.android.com/' },
  angularjs: { name: 'angularjs', url: 'http://angularjs.org/' },
  apple: { name: 'apple', url: 'https://www.apple.com/' },
  bootstrap: { name: 'bootstrap', url: 'https://getbootstrap.com/' },
  yeoman: { name: 'yeoman', url: 'https://yeoman.io/' },
  cSharp: {
    name: 'c-sharp',
    url: 'https://dotnet.microsoft.com/languages/csharp',
  },
  css3: {
    name: 'css3',
    url: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
  },
  drupal: { name: 'drupal', url: 'https://www.drupal.org/project/drupal' },
  eslint: { name: 'eslint', url: 'https://eslint.org/' },
  expo: { name: 'expo', url: 'https://expo.dev/' },
  express: { name: 'express', url: 'https://expressjs.com/' },
  flutter: { name: 'flutter', url: 'https://flutter.dev/' },
  git: { name: 'git', url: 'https://git-scm.com/' },
  graphql: { name: 'graphql', url: 'https://graphql.org/' },
  html5: {
    name: 'html5',
    url: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
  },
  java: { name: 'java', url: 'https://www.java.com/' },
  jest: { name: 'jest', url: 'https://jestjs.io/' },
  jquery: { name: 'jquery', url: 'https://jquery.com/' },
  javascript: {
    name: 'javascript',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  },
  less: { name: 'less', url: 'https://lesscss.org/' },
  linux: { name: 'linux', url: 'https://www.linux.org/' },
  mobx: { name: 'mobx', url: 'https://mobx.js.org/' },
  mongodb: { name: 'mongodb', url: 'https://www.mongodb.com/' },
  mysql: { name: 'mysql', url: 'https://www.mysql.com/' },
  nextjs: { name: 'nextjs', url: 'https://nextjs.org/' },
  nodejs: { name: 'nodejs', url: 'https://nodejs.org/' },
  php: { name: 'php', url: 'https://www.php.net/' },
  postgresql: { name: 'postgresql', url: 'https://www.postgresql.org/' },
  prettier: { name: 'prettier', url: 'https://prettier.io/' },
  rails: { name: 'rails', url: 'https://rubyonrails.org/' },
  reactRouter: { name: 'react-router', url: 'https://reactrouter.com/' },
  react: { name: 'react', url: 'https://react.dev/' },
  redux: { name: 'redux', url: 'https://redux.js.org/' },
  restApi: {
    name: 'rest-api',
    url: 'https://blog.postman.com/rest-api-examples/',
  },
  sass: { name: 'sass', url: 'https://sass-lang.com/' },
  i18next: { name: 'i18next', url: 'https://www.i18next.com/' },
  storybook: { name: 'storybook', url: 'https://storybook.js.org/' },
  styledComponents: {
    name: 'styled-components',
    url: 'https://styled-components.com/',
  },
  swift: { name: 'swift', url: 'https://developer.apple.com/swift/' },
  testingLibrary: {
    name: 'testing-library',
    url: 'https://testing-library.com/',
  },
  typescript: { name: 'typescript', url: 'https://www.typescriptlang.org/' },
  vscode: { name: 'vscode', url: 'https://code.visualstudio.com/' },
  vue: { name: 'vue', url: 'https://vuejs.org/' },
  windows: { name: 'windows', url: 'https://www.microsoft.com/' },
  wordpress: { name: 'wordpress', url: 'https://wordpress.org/' },
  sublimeText: { name: 'sublimetext', url: 'https://www.sublimetext.com/' },
  lerna: { name: 'lerna', url: 'https://lerna.js.org/' },
  nx: { name: 'nx', url: 'https://nx.dev/' },
};

const skills = [
  {
    name: 'Javascript',
    value: 90,
  },
  {
    name: 'Typescript',
    value: 75,
  },
  {
    name: 'React',
    value: 90,
  },
  {
    name: 'Jquery',
    value: 80,
  },
];

const contactConfig = {
  email: 'email@some.com',
  phone: '1234567890',
  phone_country_code: '39',
  phone_formated: '(+39)123-456789',
  address: 'Some place, Italia',
  skype: 'skype_usr',
  site: 'https://website.com',
};

const socialprofiles = {
  github: 'https://github.com',
  facebook: 'https://facebook.com',
  linkedin: 'https://linkedin.com',
  instagram: 'https://instagram.com',
};

const educationInfo = {
  education: [
    {
      id: '1',
      name: 'uni',
      location: 'Algun lugar, Argentina',
      description: 'uni_desc',
      from: '2002',
      to: '2011',
    },
    {
      id: '2',
      name: 'school',
      location: 'Bs as, Argentina',
      description: 'school_desc',
      from: '1999',
      to: '2001',
    },
  ],
  courses: [
    {
      id: '1',
      name: 'react',
      location: 'Argentina',
      description: 'react_desc',
      from: '2020',
    },
    {
      id: '1a',
      name: 'wordpress_course',
      location: 'Colombia',
      description: 'wordpress_course_desc',
      from: '2019',
    },
    {
      id: '2',
      name: 'ux_masterclass',
      location: 'Australia',
      description: 'ux_masterclass_desc',
      from: '2015',
    },
  ],
  languages: [
    {
      id: '1',
      name: 'spa',
      location: '',
      description: 'spa_desc',
    },
    {
      id: '2',
      name: 'eng',
      location: '',
      description: 'eng_desc',
    },
    {
      id: '3',
      name: 'ita',
      location: '',
      description: 'ita_desc',
    },
  ],
};

const jobInfo = [
  {
    id: '1',
    name: 'Compoany 01',
    location: 'Colombia',
    description: 'job1_desc',
    from: '2022',
    to: '2024',
    developmentStack: [
      technologies.html5,
      technologies.css3,
      technologies.javascript,
      technologies.react,
      technologies.typescript,
      technologies.nextjs,
      technologies.expo,
      technologies.redux,
      technologies.styledComponents,
      technologies.storybook,
      technologies.restApi,
      technologies.graphql,
      technologies.i18next,
      technologies.jest,
      technologies.testingLibrary,
      technologies.postgresql,
      technologies.lerna,
      technologies.nx,
    ],
    codingEnvironment: [
      technologies.apple,
      technologies.android,
      technologies.eslint,
      technologies.prettier,
      technologies.git,
      technologies.vscode,
    ],
  },
  {
    id: '2',
    name: 'Compoany 02',
    location: 'Argentina',
    description: 'job2_desc',
    from: '2021',
    to: '2025',
    developmentStack: [
      technologies.html5,
      technologies.css3,
      technologies.javascript,
      technologies.react,
      technologies.typescript,
      technologies.swift,
      technologies.jest,
      technologies.storybook,
      technologies.graphql,
      technologies.styledComponents,
      technologies.wordpress,
    ],
    codingEnvironment: [
      technologies.apple,
      technologies.android,
      technologies.eslint,
      technologies.prettier,
      technologies.git,
      technologies.vscode,
    ],
  },
  {
    id: '3',
    name: 'Compoany 03',
    location: 'Alemania',
    description: 'job3_desc',
    from: '2020',
    to: '2021',
    developmentStack: [
      technologies.html5,
      technologies.css3,
      technologies.javascript,
      technologies.react,
      technologies.expo,
      technologies.redux,
      technologies.mobx,
      technologies.storybook,
      technologies.restApi,
      technologies.mongodb,
      technologies.nodejs,
      technologies.express,
    ],
    codingEnvironment: [
      technologies.apple,
      technologies.android,
      technologies.git,
      technologies.vscode,
    ],
  },
  {
    id: '4',
    name: 'Compoany 04',
    location: 'Italia',
    description: 'job4_desc',
    from: '2011',
    to: 'PRESENT',
    developmentStack: [
      technologies.html5,
      technologies.css3,
      technologies.javascript,
      technologies.jquery,
      technologies.react,
      technologies.typescript,
      technologies.expo,
      technologies.reactRouter,
      technologies.redux,
      technologies.bootstrap,
      technologies.sass,
      technologies.yeoman,
      technologies.php,
      technologies.wordpress,
      technologies.drupal,
      technologies.i18next,
      technologies.restApi,
      technologies.jest,
      technologies.testingLibrary,
      technologies.cSharp,
      technologies.mysql,
    ],
    codingEnvironment: [
      technologies.apple,
      technologies.android,
      technologies.linux,
      technologies.eslint,
      technologies.prettier,
      technologies.git,
      technologies.sublimeText,
      technologies.vscode,
    ],
  },
];

export { skills, contactConfig, socialprofiles, educationInfo, jobInfo };
